---
- host: all
 become: true
 tasks:
 - name: Install Apache
   apt:
     name: apache2
 - name: Start Apache on boot
   service:
     name: apache2
     state: started
     enabled: true
 - name: Copy
   ansible.builtin.copy:
     scr: index13.html
     dest: /var/www/html/index31.html


